name: non-prod

# Define when this workflow should run
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
# Define the jobs
env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{inputs.app-name}}:${{ github.sha }}
jobs:
  build:
    runs-on: [self-hosted]
    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: $IMAGE_NAME

  test:
    runs-on: [self-hosted]
    container:
      image: $IMAGE_NAME
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
    - name: Run Pytest .
      run: pytest .



    