name: non-prod


# Define when this workflow should run
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      values-path:
        required: true
        type: string
      gitops-repo:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      GITOPS_REPO_TOKEN:
        required: true
# Define the jobs
env:
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/${{inputs.app-name}}:${{ github.sha }}"
jobs:
  build:
    runs-on: [self-hosted]

    steps:
    # Check out the repository
    - name: Echo the environment variable
      run: echo "The value of IMAGE_NAME is $IMAGE_NAME"
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{env.IMAGE_NAME}}

  # test:
  #   runs-on: [self-hosted]
  #   needs: build
  #   steps: 
  #     - uses: addnab/docker-run-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #         image: ${{ env.IMAGE_NAME }}
  #         run: pytest .

  # scan:
  #   runs-on: [self-hosted]
  #   needs: test
  #   steps:
  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@0.20.0
  #       with:
  #         image-ref: ${{ env.IMAGE_NAME }}
  #         format: 'table'
  #         exit-code: '1'
  #         severity: 'CRITICAL,HIGH'
  #       env:
  #         TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #         TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}


  delpoy-dev:
    runs-on: [self-hosted]
    environment: dev
    needs: build # add
    steps:
    - name: Checkout gitops repo
      uses: actions/checkout@v3
      with:
        repository: ${{inputs.gitops-repo}}
        token: ${{ secrets.GITOPS_REPO_TOKEN }} # Use a token with the appropriate permissions
    - name: Print env
      uses: mikefarah/yq@v4.44.3
      with:
        cmd: echo ${{vars.ENV_NAME}}
    - name: set env
      run: echo "VALUES_PATH=$(echo '${{ inputs.gitops_values_path }}' | sed 's/{ENV_NAME}/dev/')" >> $GITHUB_ENV
    - name: Edit yaml
      uses: mikefarah/yq@v4.44.3
      with:
        cmd: yq e '.image.tag = "${{ github.sha }}"' -i ${{env.VALUES_PATH}}
    - name: Commit changes
      env:
        GIT_SAFE_DIR: ${{ github.workspace }}
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add ${{env.VALUES_PATH}}
        git commit -m "Update tag in values file to ${{ github.sha }}"
        git push

 