name: non-prod

# Define when this workflow should run
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
# Define the jobs
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      app-name: devops-project
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}

  test:
    needs: build
    uses: ./.github/workflows/pytest.yaml
    with:
      docker-image: ${{ needs.build.outputs.image-name }}
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
