name: non-prod


# Define when this workflow should run
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      GITOPS_REPO_TOKEN:
        required: true
# Define the jobs
env:
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/${{inputs.app-name}}:${{ github.sha }}"
jobs:
  # build:
  #   runs-on: [self-hosted]
  #   steps:
  #   # Check out the repository
  #   - name: Echo the environment variable
  #     run: echo "The value of IMAGE_NAME is $IMAGE_NAME"
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3
  #   - name: Build and push
  #     uses: docker/build-push-action@v6
  #     with:
  #       push: true
  #       tags: ${{env.IMAGE_NAME}}

  # test:
  #   runs-on: [self-hosted]
  #   needs: build
  #   steps: 
  #     - uses: addnab/docker-run-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #         image: ${{ env.IMAGE_NAME }}
  #         run: pytest .

  # # scan:
  #   runs-on: [self-hosted]
  #   needs: test
  #   steps:
  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@0.20.0
  #       with:
  #         image-ref: ${{ env.IMAGE_NAME }}
  #         format: 'table'
  #         exit-code: '1'
  #         severity: 'CRITICAL,HIGH,MEDIUM'
  #       env:
  #         TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #         TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}


  delpoy-dev:
    runs-on: [self-hosted]
    container:
      image: dellnoantechnp/git-yq:latest
    # needs: build # add
    steps:
    - name: Checkout gitops repo
      uses: actions/checkout@v3
      with:
        repository: Orisade2003/gitops-devops-project
        token: ${{ secrets.GITOPS_REPO_TOKEN }} # Use a token with the appropriate permissions

    - name: Change value in YAML file
      run: |
        ls
        yq e '.image.tag = "cba1df93eb833a5cf5721320d68fd1839dfc79ea"' -i environments/dev/values/microservice-devops-values.yaml

    - name: Commit changes
      env:
        GIT_SAFE_DIR: ${{ github.workspace }}
      run: |
        cd ${{ github.workspace }}
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add environments/dev/values/${{inputs.app-name}}-values.yaml
        git commit -m "Update tag in values file"
        git push

   # - name: Checkout gitops repo
    #   uses: actions/checkout@v3
    #   with:
    #     repository: Orisade2003/gitops-devops-project
    #     token: ${{ secrets.GITOPS_REPO_TOKEN }} # Use a token with the appropriate permissions
    #     set-safe-directory: false
        # path: other-repo # Optional: Specify the directory where the repo should be checked out
    